### ISSUE TITLE
[BlackOps] Cybran Tech 3 Staging Facility Renders Offset from Placement

### ISSUE THREAD

**Issue by lhigginbotham** [aeoncleanse/Mods#105]
OS: Windows 10

The Cybran T3 Air staging facility renders offset from it's building square.  This applies to both the transparent mesh before it is built and the finished structure.  The offset also prevents structures from being built directly adjacent to the build square.

![scframe_sun_jul_10_203029_2016_00000](https://cloud.githubusercontent.com/assets/5923504/16717235/0c3ac27e-46e0-11e6-9894-cc1ee601c55e.png)

![scframe_sun_jul_10_203140_2016_00001](https://cloud.githubusercontent.com/assets/5923504/16717268/b7b69038-46e0-11e6-91b3-bf6b13048e8a.png)
Note: I disabled the cloaking for this screenshot

**Comment by aeoncleanse** [comment]
Holy crap that's appalling. Thank you for this one.

**Comment by aeoncleanse** [comment]
Hmm. I simply cannot get all four of these both centered within their build bounds AND able to fit in an even grid. @Uveso Can you take a look for me and see if you have better luck? You're looking for SkirtOffset and SkirtSize in the blueprints.

**Comment by Uveso** [comment]
Sure, i will have a look at it.

**Comment by Uveso** [comment]
Just change this:

brb5205:

```
SkirtSizeX = 12,
SkirtSizeZ = 12,
SizeX = 9,
SizeZ = 9,
SelectionThickness = 0.22,
```

And the Aeon bab5205:

```
SelectionSizeX = 6.15,
SelectionSizeZ = 6.15,
SelectionThickness = 0.22,

```

**Comment by aeoncleanse** [comment]
Selection sizes aren't relevant here. SizeX and SizeZ are changing the hitbox size.

**Comment by Uveso** [comment]
I got these values from the UEF Airstaging, it should have the same size as the cybran. At least the model has the same size. And if i test the cybran airstaging with the UEF values i can see those helperdrones correctly lined up where they should be.

Is there a way to display hitboxes ingame?

**Comment by aeoncleanse** [comment]
Yes. ctrl-alt-shift-c. We're aiming to get the footprint dimensions all the same, the green "Build Box", get the boxes to fit in a nice grid, and get each model mesh in the middle of its footprint.

**Comment by Uveso** [comment]
Here you see the UEF and Cybran Airstaging.
![as1](https://cloud.githubusercontent.com/assets/17804547/16774160/2867f364-485b-11e6-8600-2901370ff45a.png)

After setting SkirtSizeX = 12, SkirtSizeZ = 12 :
![as2](https://cloud.githubusercontent.com/assets/17804547/16774207/4f3424ea-485b-11e6-8d8e-f894773feda8.png)

if you now try to center the building with SkirtOffsetX = -1 you will get this:
![as3](https://cloud.githubusercontent.com/assets/17804547/16774248/7a718ed6-485b-11e6-9f25-7d594cc5d030.png)
As you see, you can't attach it on other buildings, because you need an SkirtOffsetX of 0.5, or 1.5 or 2.5 etc.

If you dont change the skitoffset but reduce the size of the Hitbox (SizeX+Y = 9), you will get this:
![as4](https://cloud.githubusercontent.com/assets/17804547/16774303/b6e8a05c-485b-11e6-933b-b00d49b452db.png)

The blue Hitbox fits exact the building, the green box has the same size then the UEF and you can attach the building to others.

This was what i wrote before but if you dont want that, i dont know what you mean.

**Comment by aeoncleanse** [comment]
Are you trying to tell me that changing the hitbox size adjusted the footprint? That makes no sense!

**Comment by aeoncleanse** [comment]
And yet there it is... OK, I have aeon and cybran and uef fitting nicely, but now the Seraphim one is off.

**Comment by aeoncleanse** [comment]
3f2c02825177fd53f9cc9c695d732af3b6566c13 All bar Seraphim
