### ISSUE TITLE
Sera ACU to lambda field emitter log error

### ISSUE THREAD

**Issue by Nojoke185** [aeoncleanse/Mods#126]
latest mod version downloaded...

update ACU to lambda field emitters - upgrade leads to below log errors:

WARNING: GetResource: Invalid name ""
WARNING: GetResource: Invalid name ""

similar issues seen for the later upgrades on same path

**Comment by aeoncleanse** [comment]
It appears the seraphim_shield_generator type emitters are completely missing from all BlackOps sources I have. I'll have to remove all reference to them I guess.

**Comment by aeoncleanse** [comment]
f35f82704e4fa42f0d12b25293ef1e5c4fdf1b0b

**Comment by aeoncleanse** [comment]
Nope. Needs further investigation. Despite throwing the warning, these seem to work somehow.

**Comment by aeoncleanse** [comment]
Ah, it's that the bp address is set IN the files for the artemis weapon emitters...  OK. Need to track down where this engine warning is actually being generated then! @Uveso You seem to have some experience with engine stuff. I can't get the debugger to work breakpoints into modded files, so I've been unable to track the cause so far.

**Comment by Uveso** [comment]
oh yes, this is a nice one.

WARNING: GetResource: Invalid name ""
WARNING: GetResource: Invalid name ""
Are caused by a missing unit model for LOD-1 Settings inside unit `esb0001` and `esb0002`

because there are 2 Lod settings for low and higres, there should also be 2 models on disk. The second model for Low res settings is missing. Bu we can simply use the Hires Lod-model for both Lod Settings.

The modelfile for LOD-0 is `ESB0001_LOD0.scm`
Adding  `MeshName = 'ESB0001_LOD0.scm',` to the LOD-1 will do the trick:

These are the new lod settings from esb0001:

``` LUA
            LODs = {
                {
                    LODCutoff = 100,
                    ShaderName = 'Unit',
                },
                {
                    MeshName = 'ESB0001_LOD0.scm',
                    AlbedoName = 'ESB0001_lod1_albedo.dds',
                    LODCutoff = 215,
                    ShaderName = 'Unit',
                    SpecularName = 'ESB0001_lod1_specteam.dds',
                },
            },
```

As you can see, we use for the 2nd LOD low-res textures (saved in ESB0001_lod1_albedo.dds) and a Higres Model (saved in ESB0001_LOD0.scm) at the same time.

[Edit] There also was an AnimationPermOpen with no animation file for it.
