### ISSUE TITLE
WARNING spam on game begin

### ISSUE THREAD

**Issue by aeoncleanse** [aeoncleanse/Mods#157]
There's duplicate builder spam and some missing icons. @Uveso can you help me with finding a way to get rid of these warnings?

**Comment by Uveso** [comment]
Builder Spam:

```
WARNING: Duplicate Builder detected - overriding/appending old: \000Sorian T3 Base D Engineer PD - Exp Response
WARNING: Duplicate Builder detected - overriding/appending old: \000Sorian T3 Base D Engineer PD
WARNING: Duplicate PlatoonTemplate detected - overriding/appending old: \000SorianT3BaseDefenses
WARNING: Duplicate Builder detected - overriding/appending old: \000Sorian T3 Base D Engineer PD - Exp Response R
WARNING: Duplicate PlatoonTemplate detected - overriding/appending old: \000SorianT3BaseDefenses - Emerg
WARNING: Duplicate Builder detected - overriding/appending old: \000Sorian T3 Base D Engineer PD - Light
WARNING: Duplicate PlatoonTemplate detected - overriding/appending old: \000SorianT3LightDefenses
```

These are "no" Errors.

I Added some Buildergroups to SorianDefenseBuilders.lua so the AI can build TECH3 Power defenses.
Those buildergrups are only arrays without an index. So i cant overwrite directly the corresponding buildergroup, they will added at the end of the file.

It's the same way like we hook/overwrite functions. Only difference, you will get a Warning if we do this with buildergroups.
The reason is a LUA check that will print those warnings:

GlobalBuilderTemplate.lua line 40:

```
    if Builders[arg[2].BuilderName] then
        WARN('Duplicate Builder detected - overriding/appending old: ', arg[2].BuilderName)
    [...]

```

GlobalPlatoonTemplate.lua line 37

```
    if InitialRegistration and PlatoonTemplates[arg[2].Name] then
        WARN('Duplicate PlatoonTemplate detected - overriding old: ', arg[2].Name)
    [...]

```

GlobalBuilderGroup.lua line 56

```
    if BuilderGroups[arg[2].BuilderGroupName] then
        WARN('Duplicate PlatoonTemplate detected - overriding/appending old: ', arg[2].BuilderGroupName)
    [...]

```

We could rewrite the message to a normal INFO instead of a Warning like:
`
INFO: Hooking Sorian T3 Base D Engineer PD
`

Or we can implement the T3PD builder to the maingame.
Maybe a good idea, because many MODs would need that.

[Edit]
no missing icons. (in BO unleashed)

**Comment by Uveso** [comment]
BO Advanced ACU:

`WARNING: Duplicate Builder detected - overriding/appending old: \000UEF CDR Upgrade HeavyAntiMatter
`
Its the same like the platoonbuilders. Its not an error message.

```
DEBUG: [uiutil.lua, function UIFile()] - Unable to find file:/textures/ui/uef/icons/units/esb0001_icon.dds
DEBUG: [uiutil.lua, function UIFile()] - Unable to find file:/textures/ui/uef/icons/units/esb0002_icon.dds
DEBUG: [uiutil.lua, function UIFile()] - Unable to find file:/textures/ui/uef/icons/units/esb0003_icon.dds
DEBUG: [uiutil.lua, function UIFile()] - Unable to find file:/textures/ui/uef/icons/units/esb0004_icon.dds
```

these units are created in ESL0001.lua:

```
        local unitID = 'esb000' .. unit

        local lambdaUnit = CreateUnit(unitID, self:GetArmy(),
                                      boneLocation[1], boneLocation[2], boneLocation[3],
                                      orientation[1], orientation[2], orientation[3], orientation[4], 'Land')

```

Because they are created with CreateUnit() they need an icon. So we should add one.

and we can delete these icons: (there is no unit for them)
eal0002
esl0002
eel0002
erl0002

**Comment by aeoncleanse** [comment]
I think moving the duplicate builders warning to INFO is a great plan, unless we go the route of changing it such that we don't get it at all in main game by hooking properly/better.

**Comment by Uveso** [comment]
The hook itself is working like it should. Adding a 2nd. function/array at the end of the file will always overwrite the 1st. function/array. So there is no better way.

Those check-functions are the problem. They throw errors where no error is.
And its saying `overriding/appending old:`. Thats also not true. Nothing will be appended, if there is a duplicated item. It will be always overwriten.

I will make a PR to fix the WARN messages.

**Comment by Uveso** [comment]
PR is up:
https://github.com/FAForever/fa/pull/1440

**Comment by aeoncleanse** [comment]
Will be fixed in FAF
