### ISSUE TITLE
Only T1 planes can land on the Citadel MKII (BEA0402)

### ISSUE THREAD

**Issue by Uveso** [aeoncleanse/Mods#158]
Blackrobe mentioned in the forum that the UEF Citadel only can handle TECH1 airplanes. 
Is this by design or just a error.
Makes no sense to build a experimental to support Tech1 air fighter, right ?

**Comment by Kaitane** [comment]
Since Testing Uveso's wonderful fix on the UEF Citadel Exp; both T2 & T3 air units can now land, repair, and refuel, as T1 could originally; however, the large plasma guns on each side of the Citadel, will not fire at all. Their movement seems a little odd at times to - when it seem as though it flies diagonally.
