### ISSUE TITLE
AI does not seem to manufacture T3 mobile AA units

### ISSUE THREAD

**Issue by Valarraukar** [aeoncleanse/Mods#248]
AI does not seem to manufacture T3 mobile AA units, prefers to mass produce t2 flack.

**Comment by Uveso** [comment]
Hello Valarraukar,

welcome to GitHub 💃

I tested this, and yes you are right. The AI does not build any T3 mobile land AA.
But this repository is only for Black Ops. And Black Ops hasn't any T3 mobile AA units. ;)

Please close this issue here and open a new one on our FAF game repository:
https://github.com/FAForever/fa
`[Edit] new issue is already open!`

corresponding units are (Unit-ID):
drlk001
delk002
dalk003
dslk004
drlk005

**Comment by Uveso** [comment]
@aeoncleanse 
This can be closed.
I opened a new issue https://github.com/FAForever/fa/issues/2317

**Comment by Uveso** [comment]
Fix is waiting for test/release: https://github.com/FAForever/fa/pull/2323
