### ISSUE TITLE
Cybran Stage 2 of Mazer doesn't fire/work?

### ISSUE THREAD

**Issue by aeoncleanse** [aeoncleanse/Mods#93]

**Comment by aeoncleanse** [comment]
More data needed. Works fine in my testing...

**Comment by MagHz** [comment]
Wouldn't say that it doesn't fire, but most 'direct 1v1 fire' upgrades don't seem to work for me ATM.

UEF - gatling works, upgrades seem to work properly

Aeon - beam 1 works (but is weak - maybe by design, but it's like 150 dps?); any further upgrade doesn't change the damage (beam2 improves DPS by a bit, but it's due to increasing main weapon ROF to 2; beam3 is the same as beam2)

Cybran - maser 1 works (but seems very weak, again around 100-150 dps); any further upgrades work as above. Changing damage in `unit.bp` file doesn't change anything; allso checked if I could change the range of the maser, to some value like 120 - also didn't change anything in-game.

Seraphim - gatling doesn't work at all, not getting even visuals; DPS doesn't change at all. Additionally uses gatling sound for normal weapon, even without the gatling upgrade.

Also remember that torps in Seraphim didn't work at all, but that was maybe a week ago; might have been fixed since then.

Mod version - BOPS Unleashed + ACUs; current as of 2016-07-12, downloaded maybe 2h ago. No other mods installed for testing.

supcom v3654
faf 0.11.60+577

**Comment by Uveso** [comment]
I hope i tested the right enhancement: Microwave Laser Level 2.
All 3 stages are working on. (Tested with develop main game version):
![mazercybranacu](https://cloud.githubusercontent.com/assets/17804547/16793416/1e857030-48d1-11e6-8bd0-2cee965fd671.png)
